### PR TITLE
Change texture names, to get more texture pack support by default.

### LINKED ISSUE #17: More by-default texture pack support
Most items are shared with Minetest Game, which uses a `default_` prefix for textures, so texture packs follow this.
However here, textures don't have this prefix, so texture packs don't work by default (have to write a overrides.txt for them, shame games/mods can't supply one).

For most textures this shouldn't be an issue, but for example `torch_*` is `torch_*_animated` in MTG.
Would maybe have to use a texture modifier or similar to disable it (with a modernisation option for re-enabling?).

### PR DESCRIPTION
**Pull request by GoodClover**
Closes #17.

Notes for your perusal:
> `fence` - wield-item image not a thing?
`junglegrass` - size weirdness, looks to be fine though?
`torch_on_floor` - at least Rpg16 has it at a 45deg angle
`torch[_on_ceiling]` - not really a thing - MTG uses meshes to rotate
`sign` - varieties
`furnace_front[_active]` - current `_front` texture is lit, but elsewhere is not, but `_active` is an animation.
`furnace_side` - looks weird when on top/bottom in at least REFI. _top&_bottom would look fine on sides in at least REFI.
`nc`/`nyancat` - TenPlus1 has `nyancat_*` `pbj_pup_*` `moongnu_*` which is more supported by texture packs? `pbj_pup` would match the used name & texture.
`[cooked_]rat` - not a thing?
`scorched_stuff` - not a thing?
`apple_iron` - not a thing?
`footsteps` - not a thing? (maybe do as an overlay)
`grass_side` - overlaid on top of dirt.

### CODE REVIEW

**Comment by GoodClover** [comment]
For the textures not in MTG, it would be worth looking at what is commonly in texture packs for something suitable, if not then to a mod.

For Nyan/PB&J, [TenPlus1's mod](<https://codeberg.org/tenplus1/pbj_pup/src/branch/master/textures>) has both PB&J and Nyan, here we use PB&J textures & title but Nyan internally.

For things unlikely to be elsewhere (Iron Apple, Rat, Scorched Stuff), it'd be best to add a new prefix, but leaving without would be fine too.

**Comment by GoodClover** [comment]
As for things that are animated textures but are static here, it *should* be easy to just take the first frame and stay resolution-ignorant, but I don't have high hopes…

**Comment by GoodClover** [comment]
The only things that I would like to be figured out are the `torch_on_floor` and `furnace_side` issues.
The rest I'm not too bothered about - the default texture is used.
That could be done here too, break from MTG and use a different texture name.

(To be clear, I'm seeking your thoughts.)

**Comment by sfan5** [comment]
I intentionally didn't rename the textures because this is not MTG and there are problems trying to match them.
This has the added benefit of supporting texture packs from that era (if anyone manages to still find them).

**Comment by nininik0** [comment]
> I intentionally didn't rename the textures because this is not MTG and there are problems trying to match them. This has the added benefit of supporting texture packs from that era (if anyone manages to still find them).

I have so many of those... i got some minetest-megapack-master that has TONS OF OLD COOL MODS AND TEXTURES

**Pull request closed without merging**
